apiVersion: v1
kind: Secret
metadata:
  name: springboot-todo-api-secrets
type: Opaque
stringData:
  POSTGRESQL_HOST: "<POSTGRESQL_HOST>"
  POSTGRESQL_USERNAMEERNAME: "<POSTGRESQL_USERNAME>"
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
  APPLICATIONINSIGHTS_CONNECTION_STRING: "<APP_INSIGHTS_CONNSTRING>"
